apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::557690626059:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-AXKtfBSwHKBo
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::557690626059:user/rushika
      username: rushika
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-17T11:56:18Z"
  name: aws-auth
  namespace: kube-system
  uid: 1efa1254-3c80-4e18-822c-a107b46fa39e
